default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: boiler5_development

test:
  <<: *default
  database: boiler5_test

production:
  <<: *default
  database: boiler5_production
  username: boiler5
  password: <%= ENV['BOILER5_DATABASE_PASSWORD'] %>