default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dcs_development

test:
  <<: *default
  database: dcs_test

production:
  <<: *default
  database: dcs_production
  username: dcs
  password: <%= ENV['DCS_DATABASE_PASSWORD'] %>