default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: soracv_development

test:
  <<: *default
  database: soracv_test

production:
  <<: *default
  database: soracv_production
  username: soracv
  password: <%= ENV['SORACV_DATABASE_PASSWORD'] %>